branch-defaults:
  main:
    environment: ilaravel-env
environment-defaults:
  ilaravel-env:
    branch: null
    repository: null
global:
  application_name: ilaravel
  default_ec2_keyname: null
  default_platform: PHP 8.2
  default_region: eu-central-1
  sc: git
